# Generated by Django 5.0.1 on 2024-01-09 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='название услуги')),
                ('slug', models.SlugField(verbose_name='путь')),
                ('description', models.TextField(verbose_name='описание')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='Parametr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, verbose_name='название')),
                ('description', models.CharField(max_length=50, verbose_name='информация')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parametr_service', to='service.service')),
            ],
        ),
    ]
