# Generated by Django 5.0.1 on 2024-01-09 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, verbose_name='описание')),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='advantage',
            field=models.TextField(default=1, verbose_name='приемущества'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('1', 'Пластическая хирургия'), ('2', 'Флебология'), ('3', 'Травматология и ортопедия')], default=1, max_length=40, verbose_name='категория'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(default=1, upload_to='service_image/', verbose_name='фото'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parametr',
            name='description',
            field=models.CharField(max_length=150, verbose_name='информация'),
        ),
        migrations.CreateModel(
            name='BeforAfter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='befor_after/', verbose_name='фото')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_af_bef_service', to='service.service')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100, verbose_name='вопрос')),
                ('answer', models.CharField(max_length=100, verbose_name='ответ')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_service', to='service.service')),
            ],
        ),
    ]
