# Generated by Django 5.0.1 on 2024-01-09 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_benefit_service_advantage_service_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='benefit',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='benefit_service', to='service.service'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='benefit',
            name='title',
            field=models.CharField(max_length=55, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='parametr',
            name='title',
            field=models.CharField(max_length=100, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(max_length=100, verbose_name='путь'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=100, verbose_name='название услуги'),
        ),
    ]
