# Generated by Django 5.0.1 on 2024-01-09 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_benefit_service_alter_benefit_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='имя')),
                ('text', models.TextField(verbose_name='отзыв')),
                ('phone', models.CharField(max_length=50, verbose_name='номер телефона')),
                ('date', models.DateField(auto_now_add=True, verbose_name='дата')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='RequestOfLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=50, verbose_name='номер телефона')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=50, verbose_name='номер телефона')),
                ('email', models.EmailField(max_length=254, verbose_name='почта')),
                ('operating_mode', models.CharField(max_length=50, verbose_name='режим работы')),
                ('address', models.CharField(max_length=100, verbose_name='адрес')),
                ('fecebook', models.URLField(verbose_name='фейсбук')),
                ('instagram', models.URLField(verbose_name='инстаграм')),
                ('whatsapp', models.URLField(verbose_name='ватсап')),
            ],
            options={
                'verbose_name': 'Настройка сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='имя')),
                ('experience', models.SmallIntegerField(verbose_name='стаж')),
                ('image', models.ImageField(upload_to='team/', verbose_name='фото')),
            ],
            options={
                'verbose_name': 'Учасник',
                'verbose_name_plural': 'Команда',
            },
        ),
        migrations.AlterModelOptions(
            name='beforafter',
            options={'verbose_name': 'Фото До и После', 'verbose_name_plural': 'Фото До и После'},
        ),
        migrations.AlterModelOptions(
            name='benefit',
            options={'verbose_name': 'Плюс', 'verbose_name_plural': 'Плюсы'},
        ),
        migrations.AlterModelOptions(
            name='parametr',
            options={'verbose_name': 'Параметр', 'verbose_name_plural': 'Параметры'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='имя')),
                ('email', models.EmailField(max_length=254, verbose_name='почта')),
                ('phone', models.CharField(max_length=50, verbose_name='номер телефона')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_appointment', to='service.team')),
            ],
            options={
                'verbose_name': 'Запись на прием',
                'verbose_name_plural': 'Записи на прием',
            },
        ),
    ]
