# Generated by Django 5.0.1 on 2024-01-10 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_feedback_requestofleave_setting_team_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='описание')),
                ('image', models.ImageField(upload_to='sale_image/', verbose_name='фото')),
                ('description', models.CharField(max_length=150, verbose_name='информация')),
                ('price', models.SmallIntegerField(verbose_name='цена')),
                ('first_price', models.SmallIntegerField(verbose_name='первоначальная цена')),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции',
            },
        ),
        migrations.RenameModel(
            old_name='BeforAfter',
            new_name='BeforeAfter',
        ),
    ]
