# Generated by Django 5.0.1 on 2024-01-10 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_sale_rename_beforafter_beforeafter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='отзыв'),
        ),
        migrations.AlterField(
            model_name='parametr',
            name='description',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='информация'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='description',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='информация'),
        ),
        migrations.AlterField(
            model_name='service',
            name='advantage',
            field=models.TextField(blank=True, null=True, verbose_name='приемущества'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='описание'),
        ),
    ]
