# Generated by Django 5.0.1 on 2024-01-10 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_alter_feedback_text_alter_parametr_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='doctor',
        ),
    ]
